src/assn2proj/assn2proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
               path('blog/', include('blog.urls')),
               path('admin/', admin.site.urls),
               ]

src/assn2proj/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.index, name='index'),
    path('bio', views.bio, name='bio'),
    path('techtips', views.techtips, name='techtips'),
    path('archive', views.archive, name='archive'),
    path('nuke', views.nuke, name='nuke'),
    path('init', views.init, name='init'),
    path('home', views.home, name='home'),
    path('<int:blog_id>/', views.detail, name='detail'),
    path('<int:blog_id>/post', views.post, name = 'post')

               ]

src/assn2proj/blog/models.py
from django.db import models


class Blog(models.Model):
    title_blog = models.CharField(max_length=30)
    author_blog = models.CharField(max_length=30)
    pub_date = models.DateTimeField('Date Published')
    content_blog = models.TextField()

    def __str__(self):
        return self.title_blog

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author_com = models.CharField(max_length=30)
    pub_date = models.DateTimeField('Date Published')
    content_com = models.TextField()
    email = models.CharField(max_length=100, default="email.com")
    

    def __str__(self):
        return self.author_com

src/assn2proj/blog/templates/blog/archive.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
        <title> Welcome to the Blog </title>
    </head>
    <body>
        
        <ul>
            <li>
                <a href= {% url "blog:bio" %} > Bio </a>
            </li>
            <li>
                <a href= {% url "blog:techtips" %} > Tech Tips </a>
            </li>
            <li>
                <a href= {% url "blog:home" %} > Home </a>
            </li>
        </ul>
        
        <h1> Jadon's Travel Blog </h1>
       
        <h2> Archive </h2>
        
        {% if all_blogs_list %}
            <div id="blogs" >
                {% for blog in all_blogs_list %}
                <p><a href= {% url "blog:detail" blog.id %} > <h3>  {{blog.title_blog}} </h3> </a>
                <h4>
                Author: {{blog.author_blog}}
                Date Published: {{blog.pub_date}}
                </h4>
                </p><p>
                {{ blog.content_blog|truncatewords:200 }}
                </p>
                
                <p> Number of Comments: {{ blog.comment_set.count }}</p>
                {% endfor %}
            </div>
            {% else %}
                <p> no blogs available. </p>
        {% endif %}
        
        
        
    </body>
</html>

src/assn2proj/blog/templates/blog/bio.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8"/>
         <link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
        <title> About Me </title>
    </head>
    <body>
        
        <ul>
            <li>
                <a href= {% url "blog:index" %} > Index </a>
            </li>
            <li>
                <a href= {% url "blog:techtips" %} > Tech Tips </a>
            </li>
            <li>
                <a href= {% url "blog:home" %} > Home </a>
            </li>
            <li>
                <a href= {% url "blog:archive" %} > Archive </a>
            </li>
        </ul>
        
        <h2> About Me </h2>
        <h7> Right Now it is {{ now }} </h7>
        <br></br>
        <img class= "my-face" src="{% static 'blog/traveler%20picture.jpg' %}" alt="This is me" height="300" width="300" >
            
            <h4> About my life </h4>
            
            <p> Maecenas vitae lorem id nibh interdum iaculis at egestas felis.
            Pellentesque eget risus sed ex fermentum aliquam. Curabitur in
            elementum dui, sit amet imperdiet lectus. Duis et urna ut ante
            egestas gravida. Maecenas nisl quam, porta nec consectetur ut,
            tincidunt aliquam eros. Donec tempus ultrices ligula, sit amet
            imperdiet mauris porta id. Suspendisse posuere ante sed vehicula
            bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Vivamus pulvinar arcu efficitur faucibus venenatis. Nunc lorem ante,
            condimentum eu ullamcorper eget, eleifend eu tellus. In pretium tellus
            eget lobortis rutrum. Maecenas consequat mauris non tellus tempor
            dictum. Nulla fermentum imperdiet lectus, in scelerisque arcu consectetur at. </p>
            
            <h4> Some of my favorite Foods </h4>
            <ol>
                <li> Firecracker Chicken </li>
                <li> Betos Super Nachos </li>
                <li> Waffle Love </li>
            </ol>
            
            <h3> Gallery </h3>
            
            <img src="{% static 'blog/ski.jpg' %}" alt="skiing" height="300" width="300" >
                <img src="{% static 'blog/sushi.jpg' %}" alt="sushi" height="300" width="300" >
                    <img src="{% static 'blog/zebra.jpg' %}" alt="zebra" height="300" width="300" >
                        
                        
    </body>
</html>

src/assn2proj/blog/templates/blog/detail.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
        <title> Welcome to the Blog </title>
    </head>
    <body>
        
        <ul>
            <li>
                <a href= {% url "blog:bio" %} > Bio </a>
            </li>
            <li>
                <a href= {% url "blog:techtips" %} > Tech Tips </a>
            </li>
            <li>
                <a href= {% url "blog:home" %} > Home </a>
            </li>
            <li>
                <a href= {% url "blog:archive" %} > Archive </a>
            </li>
        </ul>
        
        <h1> Jadon's Travel Blog </h1>
        
        
        
        
        {% if blog_post %}
        <div>
            
            <p><h3> {{blog_post.title_blog}}</h3>
            <h4>
                Author: {{blog_post.author_blog}}
                Date Published: {{blog_post.pub_date}}
            </h4>
            </p><p>
            {{ blog_post.content_blog}}
            </p>
            <p><b>Comments</b></p>
            {% for comment in blog_post.comment_set.all %}
            <div id="comment_box">
                
                
            <p> Nickname: {{ comment.author_com }} |
                Date Published: {{ comment.pub_date }} |
                User E-mail: {{ comment.email }}
                </p>
                <p> {{ comment.author_com }} said: </p>
                <p> "{{ comment.content_com }}" </p>
                
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p> no blogs available. </p>
        {% endif %}
        
        <div id="entry_box">
            <h4> Add Comment </h4>
            <form action = "post" method="POST">
                {% csrf_token %}
                Nickname: <input type="text" name="author_com" ><br>
                E-mail: <input type="email" name="email" ><br>
                Comment: <input type="textarea" lines="30" columns="120" name="content_com" >
                <input type="submit" value="Post" >
            </form>
        </div>
        
        
    </body>
</html>

src/assn2proj/blog/templates/blog/home.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
        <title> Welcome to the Blog </title>
    </head>
    <body>
        
        <ul>
            <li>
                <a href= {% url "blog:bio" %} > Bio </a>
            </li>
            <li>
                <a href= {% url "blog:techtips" %} > Tech Tips </a>
            </li>
            <li>
                <a href= {% url "blog:archive" %} > Archive </a>
            </li>
        </ul>
        
        <h1> Jadon's Travel Blog </h1>
        
        <h2> Home </h2>
        
        {% if recent_blogs_list %}
        <div>
            {% for blog in recent_blogs_list %}
            <p><a href= {% url "blog:detail" blog.id %} > <h3>  {{blog.title_blog}} </h3> </a>

            <h4>
                Author: {{blog.author_blog}}
                Date Published: {{blog.pub_date}}
            </h4>
            </p><p>
            {{ blog.content_blog|truncatewords:200 }}
            </p>
            <p> Number of Comments: {{ blog.comment_set.count }}</p>

            {% endfor %}
        </div>
        {% else %}
        <p> no blogs available. </p>
        {% endif %}
        
        
        
    </body>
</html>

src/assn2proj/blog/templates/blog/index.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
    <title> Welcome to the Blog </title>
</head>
<body>

<ul>
    <li>
        <a href= {% url "blog:bio" %} > Bio </a>
    </li>
    <li>
        <a href= {% url "blog:techtips" %} > Tech Tips </a>
    </li>
    <li>
        <a href= {% url "blog:home" %} > Home </a>
    </li>
    <li>
        <a href= {% url "blog:archive" %} > Archive </a>
    </li>
</ul>

<h1> Jadon's Travel Blog </h1>
<h7> Right Now it is {{ now }} </h7>
<h4> Summer Camp - August 2018 </h4>
<p class = "blog">Nam ornare risus quis massa cursus, et tristique ex sollicitudin.
    Aliquam id faucibus metus. Nunc porta auctor neque at lobortis.
    Cras porttitor felis ac sapien fringilla sodales. Maecenas tempor
    pharetra risus, nec fermentum ligula accumsan sit amet. Vestibulum
    dui lorem, varius ac lectus sed, pharetra bibendum tellus. Proin
    dapibus ut arcu in pharetra. Duis massa purus, volutpat sed dictum
    in, accumsan sed ex. Donec ligula justo, volutpat non erat sed,
    rhoncus commodo lacus. Maecenas varius rhoncus mi ac congue.
    Nullam vestibulum libero non leo pulvinar, sed tincidunt nibh
    rutrum. Nam blandit nisl vitae purus suscipit volutpat venenatis
    quis orci. Duis risus erat, molestie vitae urna ut, mattis pretium
    massa.dapibus ut arcu in pharetra. Duis massa purus, volutpat sed dictum
    in, accumsan sed ex. Donec ligula justo, volutpat non erat sed,
    rhoncus commodo lacus. Maecenas varius rhoncus mi ac congue.
    Nullam vestibulum libero non leo pulvinar, sed tincidunt nibh
</p>

<h4> Moab Trip - September 2018 </h4>
<p class = "blog" > Duis tempor ut purus non imperdiet. In tempor felis risus,
    fermentum efficitur magna varius vitae. Sed a velit lacus. dapibus ut
    arcu in pharetra. Duis massa purus, volutpat sed dictum
    in, accumsan sed ex. Donec ligula justo, volutpat non erat sed,
    rhoncus commodo lacus. Maecenas varius rhoncus mi ac congue.
    Nullam vestibulum libero non leo pulvinar, sed tincidunt nibhIn aliquam sapien sed
    turpis pretium, nec fermentum magna ullamcorper. Phasellus ligula libero,
    aliquam in maximus vel, fringilla quis nibh. Donec ornare odio a tincidunt
    lacinia. Curabitur sit amet molestie mauris. In fringilla nec tortor ac porta.
    Ut eget elit ut orci tincidunt auctor. Nulla tempus odio a nunc volutpat,
    feugiat commodo nulla ultrices. Duis commodo ligula vel imperdiet blandit. </p>

<br /> <br />

<h2>Upcoming Trips</h2>
<h4>New York - February 2019</h4>
<p class = "blog" >Etiam molestie tellus non nisl eleifend, nec pulvinar ligula elementum.
    Etiam a eros elementum tellus viverra fringilla rhoncus ullamcorper justo.
    Sed in efficitur dui. Integer eleifend non quam sit amet euismod. Cras
    fermentum odio id tortor gravida, vitae consectetur sem rhoncus. Phasellus
    in volutpat metus. Vivamus imperdiet felis vitae enim accumsan venenatis.
    Praesent dignissim ultrices mi at faucibus. Aenean ut orci felis. Ut vitae
    urna a est aliquam placerat id vitae sapien. In vitae tristique diam. Duis
    malesuada a magna sit amet bibendum. Mauris lacinia diam neque, id auctor
    libero tincidunt quis. Vivamus vel nunc ut metus venenatis gravida. dapibus
    ut arcu in pharetra. Duis massa purus, volutpat sed dictum
    in, accumsan sed ex. Donec ligula justo, volutpat non erat sed,
    rhoncus commodo lacus. Maecenas varius rhoncus mi ac congue.
    Nullam vestibulum libero non leo pulvinar, sed tincidunt nibh</p>



</body>
</html>

src/assn2proj/blog/templates/blog/techtips.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}"/>
    <title> Tech Tips </title>
</head>
<body>
<ul>
    <li>
        <a href= {% url "blog:index" %} > Index </a>
    </li>
    <li>
        <a href= {% url "blog:bio" %} > Bio </a>
    </li>
    <li>
        <a href= {% url "blog:home" %} > Home </a>
    </li>
    <li>
        <a href= {% url "blog:archive" %} > Archive </a>
    </li>
</ul>

<h1> Git Cheat Sheet </h1>
<h7> Right Now it is {{ now }} </h7>
<p id="intro">Use these tips to quickly set up a repository and make commits to it!</p>

<br/>

<div>
    <table>
        <tr>
            <th> Git Command </th>
            <th> Description </th>
            <th> Example </th>
        </tr>
        <tr>
            <td>git init</td>
            <td> Creates a repository with the name as the argument</td>
            <td> <code> git init cs2610-riggs-jadon-assn1 </code></td>
        </tr>
        <tr>
            <td> git add </td>
            <td> Adds all files you list to the "deck", to be committed </td>
            <td> <code> git add my-file.html </code></td>
        </tr>
        <tr>
            <td> git status </td>
            <td> check status of updated or untouched files </td>
            <td> <code> git status </code></td>
        </tr>
    </table>
</div>

</body>
</html>